# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shuxinshibie.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1161, 846)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(500, 20, 201, 51))
        self.label.setStyleSheet("font: 24pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.toolBox = QtWidgets.QToolBox(Form)
        self.toolBox.setGeometry(QtCore.QRect(20, 70, 1111, 761))
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QtWidgets.QWidget()
        self.toolBoxPage1.setGeometry(QtCore.QRect(0, 0, 1111, 683))
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.tabWidget = QtWidgets.QTabWidget(self.toolBoxPage1)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1081, 681))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(20, 21, 1051, 191))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(50, 240, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 230, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(920, 230, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 360, 1061, 251))
        self.listWidget_3.setObjectName("listWidget_3")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(20, 290, 1051, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(950, 620, 81, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 201, 31))
        self.label_2.setStyleSheet("\n"
"font: 14pt \"微软雅黑\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(440, 20, 331, 31))
        self.comboBox.setObjectName("comboBox")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 80, 1051, 201))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(800, 20, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 300, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(670, 300, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_3.setGeometry(QtCore.QRect(40, 350, 1041, 23))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.listWidget_7 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_7.setGeometry(QtCore.QRect(20, 401, 1051, 201))
        self.listWidget_7.setObjectName("listWidget_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(950, 620, 81, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.toolBox.addItem(self.toolBoxPage1, "")
        self.toolBoxPage2 = QtWidgets.QWidget()
        self.toolBoxPage2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.toolBox.addItem(self.toolBoxPage2, "")
        self.toolBoxPage3 = QtWidgets.QWidget()
        self.toolBoxPage3.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.toolBoxPage3.setObjectName("toolBoxPage3")
        self.toolBox.addItem(self.toolBoxPage3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_7.clicked.connect(Form.denglu_pane_show)
        self.pushButton_8.clicked.connect(Form.denglu_pane_show)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "目标属性识别"))
        self.pushButton.setText(_translate("Form", "添加"))
        self.pushButton_2.setText(_translate("Form", "删除"))
        self.pushButton_3.setText(_translate("Form", "识别"))
        self.pushButton_8.setText(_translate("Form", "返回"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "本地图片"))
        self.label_2.setText(_translate("Form", "请输入网址："))
        self.pushButton_4.setText(_translate("Form", "搜索"))
        self.pushButton_5.setText(_translate("Form", "删除"))
        self.pushButton_6.setText(_translate("Form", "识别"))
        self.pushButton_7.setText(_translate("Form", "返回"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "网络图片"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), _translate("Form", "选择图片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

