# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '打算好好做的音乐播放器.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 694)
        MainWindow.setMinimumSize(QtCore.QSize(996, 694))
        MainWindow.setMaximumSize(QtCore.QSize(996, 694))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.left_widget = QtWidgets.QWidget(self.main_widget)
        self.left_widget.setObjectName("left_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.left_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.left_button_5 = QtWidgets.QPushButton(self.left_widget)   #5
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_5.setIcon(icon)
        self.left_button_5.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_5, 8, 0, 1, 3)
        self.left_button_7 = QtWidgets.QPushButton(self.left_widget)  #7
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/action_log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_7.setIcon(icon1)
        self.left_button_7.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_7, 11, 0, 1, 3)
        self.left_mini = QtWidgets.QPushButton(self.left_widget)
        self.left_mini.setMaximumSize(QtCore.QSize(51, 16777215))
        self.left_mini.setObjectName("left_mini")
        self.gridLayout_3.addWidget(self.left_mini, 0, 2, 1, 1)
        self.left_visit = QtWidgets.QPushButton(self.left_widget)
        self.left_visit.setMaximumSize(QtCore.QSize(43, 16777215))
        self.left_visit.setObjectName("left_visit")
        self.gridLayout_3.addWidget(self.left_visit, 0, 1, 1, 1)
        self.left_close = QtWidgets.QPushButton(self.left_widget)
        self.left_close.setMaximumSize(QtCore.QSize(38, 16777215))
        self.left_close.setObjectName("left_close")
        self.gridLayout_3.addWidget(self.left_close, 0, 0, 1, 1)
        self.left_label_3 = QtWidgets.QPushButton(self.left_widget)
        self.left_label_3.setObjectName("left_label")
        self.gridLayout_3.addWidget(self.left_label_3, 9, 0, 1, 3)
        self.left_button_6 = QtWidgets.QPushButton(self.left_widget) #6
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/acorn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_6.setIcon(icon2)
        self.left_button_6.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_6, 10, 0, 1, 3)
        self.left_button = QtWidgets.QPushButton(self.left_widget)   #1
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/at_sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button.setIcon(icon3)
        self.left_button.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button, 3, 0, 1, 3)
        self.left_button_3 = QtWidgets.QPushButton(self.left_widget) #3
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/add_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_3.setIcon(icon4)
        self.left_button_3.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_3, 6, 0, 1, 3)
        self.left_button_4 = QtWidgets.QPushButton(self.left_widget)  #4
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/action.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_4.setIcon(icon5)
        self.left_button_4.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_4, 7, 0, 1, 3)
        self.left_label = QtWidgets.QPushButton(self.left_widget)
        self.left_label.setObjectName("left_label")
        self.gridLayout_3.addWidget(self.left_label, 1, 0, 1, 3)
        self.letf_button = QtWidgets.QPushButton(self.left_widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/acoustic_guitar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.letf_button.setIcon(icon6)
        self.letf_button.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.letf_button, 2, 0, 1, 3)
        self.left_label_2 = QtWidgets.QPushButton(self.left_widget)
        self.left_label_2.setObjectName("left_label")
        self.gridLayout_3.addWidget(self.left_label_2, 5, 0, 1, 3)
        self.left_button_2 = QtWidgets.QPushButton(self.left_widget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/draw_eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_2.setIcon(icon7)
        self.left_button_2.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_2, 4, 0, 1, 3)
        self.left_button_8 = QtWidgets.QPushButton(self.left_widget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/agp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_8.setIcon(icon8)
        self.left_button_8.setObjectName("left_button")
        self.gridLayout_3.addWidget(self.left_button_8, 12, 0, 1, 3)
        self.gridLayout_2.addWidget(self.left_widget, 0, 0, 1, 1)

        self.right_widget = QtWidgets.QWidget(self.main_widget)
        self.right_widget.setObjectName("right_widget")                              #right widget
        self.gridLayout_4 = QtWidgets.QGridLayout(self.right_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.songlist_widget = QtWidgets.QWidget(self.right_widget)
        self.songlist_widget.setObjectName("songlist_widget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.songlist_widget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.right_newsong_widget = QtWidgets.QWidget(self.songlist_widget)
        self.right_newsong_widget.setObjectName("right_newsong_widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.right_newsong_widget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.right_newsong_widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.right_newsong_widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 4, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.right_newsong_widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_10.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.right_newsong_widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.right_newsong_widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_10.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.right_newsong_widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_10.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.right_newsong_widget, 0, 0, 1, 1)
        self.right_playlist_widget = QtWidgets.QWidget(self.songlist_widget)
        self.right_playlist_widget.setObjectName("right_playlist_widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.right_playlist_widget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.toolButton = QtWidgets.QToolButton(self.right_playlist_widget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("05530725a658de394b63f307e65b0c44.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon9)
        self.toolButton.setIconSize(QtCore.QSize(100, 100))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_11.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.right_playlist_widget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("cf61536f3227d533b5910789b217005d.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon10)
        self.toolButton_2.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton")
        self.gridLayout_11.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.right_playlist_widget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ee52bf97efcc18cef34bc1fe6848a87a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon11)
        self.toolButton_3.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton")
        self.gridLayout_11.addWidget(self.toolButton_3, 1, 0, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.right_playlist_widget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("bce5548245bc51c4ccc7f350651f7153.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon12)
        self.toolButton_4.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton")
        self.gridLayout_11.addWidget(self.toolButton_4, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.right_playlist_widget, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.songlist_widget, 4, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.right_widget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 3))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 5, 0, 1, 1)
        self.recommend_widget = QtWidgets.QWidget(self.right_widget)
        self.recommend_widget.setObjectName("recommend_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.recommend_widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.right_recommend_label = QtWidgets.QLabel(self.recommend_widget)
        self.right_recommend_label.setObjectName("right_lable")
        self.gridLayout_6.addWidget(self.right_recommend_label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.recommend_widget, 1, 0, 1, 1)
        self.right_recommend_widge = QtWidgets.QWidget(self.right_widget)
        self.right_recommend_widge.setObjectName("right_recommend_widge")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.right_recommend_widge)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.recommend_button_1 = QtWidgets.QToolButton(self.right_recommend_widge)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("4dac789a58ab6be1c0ad1ffb7cfcc394.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recommend_button_1.setIcon(icon13)
        self.recommend_button_1.setIconSize(QtCore.QSize(100, 100))
        self.recommend_button_1.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.recommend_button_1.setObjectName("recommend_button_1")
        self.gridLayout_7.addWidget(self.recommend_button_1, 0, 0, 1, 1)
        self.recommend_button_2 = QtWidgets.QToolButton(self.right_recommend_widge)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("9ce117e72f233ebfdc8adcc6abff22ce.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recommend_button_2.setIcon(icon14)
        self.recommend_button_2.setIconSize(QtCore.QSize(100, 100))
        self.recommend_button_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.recommend_button_2.setObjectName("recommend_button_2")
        self.gridLayout_7.addWidget(self.recommend_button_2, 0, 1, 1, 1)
        self.recommend_button_3 = QtWidgets.QToolButton(self.right_recommend_widge)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("14c53ab8c948dbd1a22ea001fb0f0f53.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recommend_button_3.setIcon(icon15)
        self.recommend_button_3.setIconSize(QtCore.QSize(100, 100))
        self.recommend_button_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.recommend_button_3.setObjectName("recommend_button_3")
        self.gridLayout_7.addWidget(self.recommend_button_3, 0, 2, 1, 1)
        self.recommend_button_4 = QtWidgets.QToolButton(self.right_recommend_widge)
        self.recommend_button_4.setIcon(icon12)
        self.recommend_button_4.setIconSize(QtCore.QSize(100, 100))
        self.recommend_button_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.recommend_button_4.setObjectName("recommend_button_4")
        self.gridLayout_7.addWidget(self.recommend_button_4, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.right_recommend_widge, 2, 0, 1, 1)
        self.new_song_widget = QtWidgets.QWidget(self.right_widget)
        self.new_song_widget.setObjectName("new_song_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.new_song_widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.right_label = QtWidgets.QLabel(self.new_song_widget)
        self.right_label.setObjectName("right_lable")           #right label
        self.gridLayout_8.addWidget(self.right_label, 0, 0, 1, 1)
        self.right_label_2 = QtWidgets.QLabel(self.new_song_widget)
        self.right_label_2.setObjectName("right_lable")         #right label
        self.gridLayout_8.addWidget(self.right_label_2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.new_song_widget, 3, 0, 1, 1)
        self.right_bar_widget = QtWidgets.QWidget(self.right_widget)
        self.right_bar_widget.setObjectName("right_bar_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.right_bar_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.search_icon = QtWidgets.QLabel(self.right_bar_widget)
        self.search_icon.setObjectName("search_icon")
        self.gridLayout_5.addWidget(self.search_icon, 0, 1, 1, 1)
        self.right_bar_widget_search_input = QtWidgets.QLineEdit(self.right_bar_widget)
        self.right_bar_widget_search_input.setObjectName("right_bar_widget_search_input")
        self.gridLayout_5.addWidget(self.right_bar_widget_search_input, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.right_bar_widget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("WinForm开发经典图标素材 3870个图标/icon(3800)/boxtrapper.png"))
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.right_bar_widget, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.right_widget)
        self.widget.setObjectName("widget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("QT小图标/actions/stock_media-rew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon16)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_12.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("QT小图标/actions/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon17)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_12.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("QT小图标/actions/gtk-media-forward-ltr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon18)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_12.addWidget(self.pushButton_9, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(299, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.right_widget, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 8)
        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_button_5.setText(_translate("MainWindow", "我的收藏"))
        self.left_button_7.setText(_translate("MainWindow", "关注我们"))
        self.left_mini.setText(_translate("MainWindow", ""))
        self.left_visit.setText(_translate("MainWindow", ""))
        self.left_close.setText(_translate("MainWindow", ""))
        self.left_label_3.setText(_translate("MainWindow", "联系与帮助"))
        self.left_button_6.setText(_translate("MainWindow", "反馈建议"))
        self.left_button.setText(_translate("MainWindow", "在线FM"))
        self.left_button_3.setText(_translate("MainWindow", "本地音乐"))
        self.left_button_4.setText(_translate("MainWindow", "下载管理"))
        self.left_label.setText(_translate("MainWindow", "每日推荐"))
        self.letf_button.setText(_translate("MainWindow", "华语流行"))
        self.left_label_2.setText(_translate("MainWindow", "我的音乐"))
        self.left_button_2.setText(_translate("MainWindow", "热门MV"))
        self.left_button_8.setText(_translate("MainWindow", "遇到问题"))
        self.pushButton_2.setText(_translate("MainWindow", "sjdfkjsdklfj jdflskdj "))
        self.pushButton_4.setText(_translate("MainWindow", "sjdfjsklfj djfklsjdk jdfksjdk "))
        self.pushButton.setText(_translate("MainWindow", "kdfjslfkjsd fskjfksdjfs  djsfjs"))
        self.pushButton_3.setText(_translate("MainWindow", "jfklsjdlkfjsdlk  djsfkjsdlkfjs jdslkfjsk"))
        self.pushButton_5.setText(_translate("MainWindow", "sdjflsjfks jsdkfjskdjf dsjkfjs "))
        self.pushButton_6.setText(_translate("MainWindow", "sjfslkjfkls  fjskldjflskjf  jskldjflsdk"))
        self.toolButton.setText(_translate("MainWindow", "无法打破的肌肤快"))
        self.toolButton_2.setText(_translate("MainWindow", "发送到发送到发送"))
        self.toolButton_3.setText(_translate("MainWindow", "对方水电费是的浮"))
        self.toolButton_4.setText(_translate("MainWindow", "尖峰时刻路径分离"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.right_recommend_label.setText(_translate("MainWindow", "今日推荐"))
        self.recommend_button_1.setText(_translate("MainWindow", "我的最爱"))
        self.recommend_button_2.setText(_translate("MainWindow", "你喜欢的"))
        self.recommend_button_3.setText(_translate("MainWindow", "他喜欢的"))
        self.recommend_button_4.setText(_translate("MainWindow", "她喜欢的"))
        self.right_label.setText(_translate("MainWindow", "最新歌曲"))
        self.right_label_2.setText(_translate("MainWindow", "热门歌单"))
        self.search_icon.setText(_translate("MainWindow", " 搜索 "))
        self.right_bar_widget_search_input.setPlaceholderText(_translate("MainWindow", " 请输入歌手名字或者歌曲的名字点击回车进行搜索"))

import image2_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

